// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type BrandTableRow = {
    id: string;
    name: string;
    description: string;
    product: { nodes: ProductTableRow[] };
  };

  type CategoryTableRow = {
    id: string;
    name: string;
    description: string;
    product1: { nodes: Product1TableRow[] };
    productsCount: number;
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
  };

  type ProductTableRow = {
    id: string;
    name: string;
    description: string;
    brand: BrandTableRow;
    category: CategoryTableRow;
    image: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
    };
    write: {
      email: string;
      password: string;
    };
    params: {};
    actions: {};
  };

  type AllProductViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      brand: BrandTableRow;
      category: CategoryTableRow;
      image: string;
    };
    write: {
      name: string;
      description: string;
      brand: string[];
      category: string[];
      image: string;
    };
    params: {};
    actions: {};
  };

  type AllBrandViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
  };

  type AllCategoryViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      productsCount: number;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    allProduct: AllProductViewRow;
    allBrand: AllBrandViewRow;
    allCategory: AllCategoryViewRow;
  };
}
